namespaces:
  - name: new-dev-api
    apps:
      - name: finance-ms
        image: newrepo.azurecr.io/finance-ms:Version-2025.02.10-12.45.00-Release
        port: 6004
        configMapRef: new-finance-api-configmap
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
        autoscaling:
          minReplicas: 3
          maxReplicas: 12
          targetCPUUtilizationPercentage: 65
          targetMemoryUtilizationPercentage: 75
      - name: payments-ms
        image: newrepo.azurecr.io/payments-ms:stable
        port: 6005
        configMapRef: new-payments-api-configmap
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        autoscaling:
          minReplicas: 2
          maxReplicas: 7
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80
  - name: new-prod-api
    apps:
      - name: finance-ms
        image: newprodrepo.azurecr.io/finance-ms:stable
        port: 6004
        configMapRef: new-finance-api-configmap
        resources:
          requests:
            cpu: "600m"
            memory: "1Gi"
          limits:
            cpu: "1200m"
            memory: "2Gi"
        autoscaling:
          minReplicas: 4
          maxReplicas: 18
          targetCPUUtilizationPercentage: 60
          targetMemoryUtilizationPercentage: 70
