namespaces:
  dev-environment:
    apps:
      service1:
        name: app-service-1
        image: myrepo.azurecr.io/app-service-1:2025.01.02-17.24.31
        port: 5001
        replicas: 1
        configMapRef: configmap-service-1
        ingressHost: app-service-1.mydomain.com
        tlsSecret: tls-secret-service-1

      service2:
        name: app-service-2
        image: myrepo.azurecr.io/app-service-2:2025.01.02-17.24.31
        port: 5002
        replicas: 1
        configMapRef: configmap-service-2
        ingressHost: app-service-2.mydomain.com
        tlsSecret: tls-secret-service-2

  test-environment:
    apps:
      service1:
        name: app-service-3
        image: myrepo.azurecr.io/app-service-3:2025.01.02-17.24.31
        port: 5003
        replicas: 1
        configMapRef: configmap-service-3
        ingressHost: app-service-3.mydomain.com
        tlsSecret: tls-secret-service-3

      service2:
        name: app-service-4
        image: myrepo.azurecr.io/app-service-4:2025.01.02-17.24.31
        port: 5004
        replicas: 1
        configMapRef: configmap-service-4
        ingressHost: app-service-4.mydomain.com
        tlsSecret: tls-secret-service-4


  # Add other namespaces & apps...
