{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .namespaces }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      imagePullSecrets:
        - name: {{ .imagePullSecrets.name }}
      containers:
        - name: {{ .name }}
          image: "{{ .image }}"
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - configMapRef:
                name: {{ .configMapRef }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
---
{{- end }}
