{{- range .Values.apps }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Environment }}-ingress-{{ .name }}
  namespace: {{ .namespaces }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issuer-certificate-renewal: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .URL }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: lb-service-{{ .name }}
            port:
              number: 80
  tls:
  - hosts:
    - "{{ .URL }}"
    secretName: {{ .Environment }}-tls-secret-{{ .name }}
---
{{- end }}
