{{- range .Values.namespaces }}
{{- range .apps }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pz-dev-ingress-{{ .name }}
  namespace: {{ $.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issuer-certificate-renewal: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .name }}-api.icaniotech.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: pz-lb-service-{{ .name }}
            port:
              number: 80
  tls:
  - hosts:
    - "{{ .name }}-api.icaniotech.com"
    secretName: pz-dev-tls-secret-{{ .name }}
---
{{- end }}
{{- end }}
