{{- range .Values.namespaces }}
{{- range .apps }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.name }}
  name: pz-lb-service-{{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
---
{{- end }}
{{- end }}
