{{- range $namespace, $data := .Values.namespaces }}
{{- range $key, $app := $data.apps }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: pz-lb-service-{{ $app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $app.port }}
  selector:
    app: {{ $app.name }}
{{- end }}
{{- end }}
