{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .namespaces }}
  name: lb-service-{{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
---
{{- end }}
